# Site settings
title: Minimal Staticman v3 Demo
subtitle: A barebone GitHub Pages with static comments
email: your-email@domain.com
description: Test
baseurl: ""
url: "https://api-oszkar.github.io/TestStaticmanLab/"
locale: en
github_username:  api-oszkar

# Build settings
markdown: kramdown

staticman:
  api: "https://static-man-api.herokuapp.com/v3/entry/github/api-oszkar/TestStaticmanLab/master/comments"
  path: "_data/comments/test-slug"
